# Makefile
# 
# Objetivo: Exemplo passo a passo da lógica dos arquivos Makefile.
#
# Versão 1.0
#
# Programador: Marcus Marinho Bezerra (marcusmarinhob) 29/05/2020
#
# Email: marcusmarinhob@gmail.com

all:	mensagem

	@echo "Olá mundo Makefile!"

mensagem:
	
	@echo "Mensagem!!"
	
mensagem2:
	@echo "Mensagem2!!"

criarDiretorio:
	@mkdir Diretorio
