# Makefile
# 
# Objetivo: Exemplo passo a passo da lógica dos arquivos Makefile.
#
# Versão 1.0
#
# Programador: Marcus Marinho Bezerra (marcusmarinhob) 29/05/2020
#
# Email: marcusmarinhob@gmail.com

all:
	@echo "COMPILAÇÃO:"
	@echo "======================================="
	@echo "Compilando arquivo main.c com Makefile!"
	@gcc main.c -o main.exe
	@echo "Arquivo compilado com sucesso!"
	@echo
	@echo	
	@echo "EXECUÇÃO:"
	@echo "======================================="
	@echo "Executando main.exe: "
	@echo
	@./main.exe


